### ISSUE TITLE
Install fail, instructed to update Node & NPM, both are current.

### ISSUE THREAD

**Issue by andrewlintz** [nirajpandkar/gtip#1]
osx, npm v3.10.6, node v6.4.0, 

**Description: issue was discovered by:**
Entering into terminal: npm install --global git-tip

**Received Error message:** 

`/usr/local/bin/git-tip -> /usr/local/lib/node_modules/git-tip/index.js`

`> git-tip@1.2.2 postinstall /usr/local/lib/node_modules/git-tip`
`> wget https://raw.githubusercontent.com/git-tips/tips/master/tips.json -O tips.json`

`sh: wget: command not found`
`npm ERR! Darwin 15.6.0`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "git-tip"`
`npm ERR! node v6.4.0`
`npm ERR! npm  v3.10.6`
`npm ERR! file sh`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno ENOENT`
`npm ERR! syscall spawn`

`npm ERR! git-tip@1.2.2 postinstall: wget https://raw.githubusercontent.com/git-tips/tips/master/tips.json -O tips.json`
`npm ERR! spawn ENOENT`
`npm ERR!`
`npm ERR! Failed at the git-tip@1.2.2 postinstall script 'wget https://raw.githubusercontent.com/git-tips/tips/master/tips.json -O tips.json'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the git-tip package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     wget https://raw.githubusercontent.com/git-tips/tips/master/tips.json -O tips.json`
`npm ERR! You can get information on how to open an issue for this project with:`
`npm ERR!     npm bugs git-tip`
`npm ERR! Or if that isn't available, you can get their info via:`
`npm ERR!     npm owner ls git-tip`
`npm ERR! There is likely additional logging output above.`  

**suspected issues:**
`> wget https://raw.githubusercontent.com/git-tips/tips/master/tips.json -O tips.json`

`sh: wget: command not found`

**Comment by nirajpandkar** [comment]
Oh! First of all thanks for taking out time for the issue.
Over here `wget` is being used to download the [`tips.json`](https://github.com/git-tips/tips/blob/master/tips.json) file from [this](https://github.com/git-tips/tips) project.

I've never worked on OSX but a quick search led me to this - 
**Possible Solution**: 
1. Install `wget` with Homebrew package manager - [Link](http://stackoverflow.com/questions/4572153/os-x-equivalent-of-linuxs-wget/17094214#17094214)
2. Without Homebrew - [Link](http://stackoverflow.com/a/19767581/4411757)

**Note**: You can take a look at other alternative answers too.

Thanks for pointing it out. I'll be sure to update the README accordingly. Also ping me once its working or even if any problems occur.

**Comment by andrewlintz** [comment]
Having Homebrew already installed, a quick `brew install wget` did the trick.  Git-tip installed perfectly, and I'm enjoying it. 

Probably should have poked around google for wget... but at least this is bug is known. 

Thank you.

**Comment by nirajpandkar** [comment]
Glad you liked it :smile:

**Comment by gerrywastaken** [comment]
@nirajpandkar are a lot of people going to run into this issue?

During install I got
```
error ~/.config/yarn/global/node_modules/git-tip: Command failed.
Exit code: 127
Command: wget https://raw.githubusercontent.com/git-tips/tips/master/tips.json -O tips.json
```

Running `brew install wget` fixed the issue for me, but first I had to come here and find this closed issue. I imagine many just give up before that.

**Comment by nirajpandkar** [comment]
Oh yeah. I forgot to add the dependency for OSX users in the README. I will get on it ASAP. But if you want to create a pull request feel free :)
