### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by iamaaditya** [nirajpandkar/gtip#2]
$ git-tip                                                                                     

/usr/local/lib/node_modules/git-tip/index.js:33
const cli = meow(`
                 ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by iamaaditya** [comment]
So I am guessing not all systems (non ES6) take the backtick. 
I fixed it by using string concatenation "+" and having multiline string.
(posting incase people search for the issue)

**Comment by nirajpandkar** [comment]
Thanks for pointing that out :+1: I should've considered that.

Could you post your replacement for the ES6 part here? I'll keep this issue open for others.

**Comment by nirajpandkar** [comment]
@iamaaditya ping?

**Comment by iamaaditya** [comment]
I have submitted the pull request. This can be safely merged as using "+" for multi-line comment is supported on all systems and is also preferred by [Google JS Style Guide](https://google.github.io/styleguide/javascriptguide.xml)
